### ISSUE TITLE
Docs 404

### ISSUE THREAD

**Issue by oraNod** [ansible-community/antsibull-tool#9]
Go to https://ansible.readthedocs.io/projects/antsibull-tool/ 

https://github.com/ansible-community/antsibull-tool/blob/main/docs/index.md and https://github.com/ansible-community/antsibull-tool/blob/main/README.md

Do the docs need to be imported into the ansible namespace as a subproject?

**Comment by felixfontein** [comment]
Right, that's also a thing that's still missing :)

> Do the docs need to be imported into the ansible namespace as a subproject?

I think so, but I don't really remember how it worked for antsibull-docs and ansible-build-data and antsibull-changelog...

**Comment by oraNod** [comment]
Ah, OK. Yeah I see there's not a project in RTD for it. I could import it and create the project if you like. Of course I'll add you as a maintainer.

For the other projects, I added them as subprojects in the ansible namespace. When we've got this one imported, I'll take care of doing that too.

**Comment by felixfontein** [comment]
If you have time, please try. Thanks :) Otherwise I'll try this evening...

**Comment by oraNod** [comment]
@felixfontein I've set things up in RTD and sent you a maintainer invite. Give me a shout if there's anything else.

**Comment by felixfontein** [comment]
Thanks, it works great!
